services:
  adam:
    build: .
    container_name: adam-agent
    restart: unless-stopped
    environment:
      # Override with environment variables if needed
      - LINEAR_API_KEY=${LINEAR_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_USERNAME=${GITHUB_USERNAME}
      - GITHUB_EMAIL=${GITHUB_EMAIL}
      - BASE_BRANCH=${BASE_BRANCH:-main}
      - DEBUG=${DEBUG:-false}
      - POLL_INTERVAL=${POLL_INTERVAL:-30}
      - REPOS_DIR=${REPOS_DIR:-./repos}
    volumes:
      # Mount a volume for persistent git repositories
      - adam_repos:/app/repos
      # Mount source code if available (for development with live updates)
      # When a volume is mounted here, it will override the copied source code
      - ${SOURCE_MOUNT:-.}:/app
      # Exclude node_modules to avoid conflicts between host and container
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - adam-network

volumes:
  adam_repos:
    driver: local

networks:
  adam-network:
    driver: bridge